// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaaLzbFjVACXawl2ytWUAuFisWZl0eKk4',
    appId: '1:91438560795:web:75ef49bee9905618892abe',
    messagingSenderId: '91438560795',
    projectId: 'mox-beta',
    authDomain: 'mox-beta.firebaseapp.com',
    databaseURL: 'https://mox-beta-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mox-beta.firebasestorage.app',
    measurementId: 'G-606MHR6W71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqrRUvXcUro39cdoKLPKBi20zmJdemdk',
    appId: '1:91438560795:android:f41dec7a8ea28ee9892abe',
    messagingSenderId: '91438560795',
    projectId: 'mox-beta',
    databaseURL: 'https://mox-beta-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mox-beta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlX-kFmDWOpqj4BC_F2eSgg-SETWGx-a4',
    appId: '1:91438560795:ios:9dec1bd22fe10a4b892abe',
    messagingSenderId: '91438560795',
    projectId: 'mox-beta',
    databaseURL: 'https://mox-beta-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mox-beta.firebasestorage.app',
    iosBundleId: 'com.messengermoxbeta.moxBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlX-kFmDWOpqj4BC_F2eSgg-SETWGx-a4',
    appId: '1:91438560795:ios:9dec1bd22fe10a4b892abe',
    messagingSenderId: '91438560795',
    projectId: 'mox-beta',
    databaseURL: 'https://mox-beta-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mox-beta.firebasestorage.app',
    iosBundleId: 'com.messengermoxbeta.moxBeta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaaLzbFjVACXawl2ytWUAuFisWZl0eKk4',
    appId: '1:91438560795:web:5975b2f6bc4cd39d892abe',
    messagingSenderId: '91438560795',
    projectId: 'mox-beta',
    authDomain: 'mox-beta.firebaseapp.com',
    databaseURL: 'https://mox-beta-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mox-beta.firebasestorage.app',
    measurementId: 'G-5MTVMNQV3M',
  );
}
